FROM maven:3.9.9-eclipse-temurin-21

WORKDIR /app

COPY .mvn/ .mvn/
COPY mvnw pom.xml ./

RUN chmod +x mvnw && ./mvnw -q -DskipTests dependency:go-offline

COPY src ./src

CMD ["./mvnw", "spring-boot:run"]